# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  dev:
    desc: "run server in dev mode"
    cmd: go run cmd/http/main.go

  compose:up:
    desc: "start all docker containers"
    cmd: docker compose up -d

  compose:down:
    desc: "stop all docker containers"
    cmd: docker compose down

  db:cli:
    desc: "run db cli"
    cmd: docker exec -it postgres psql -U {{ .DB_USER }} -b {{ .DB_NAME }}
